version: "3.7"
services:
  app:
    build:
      context: .
    image: htmx-ruby
    volumes:
      - ".:/opt/server"
    ports:
      - "8080:8080"
    env_file:
      - .env
    expose:
      - "8080"
    command: bundle exec rackup -p 8080 -o 0.0.0.0 config.ru