version: "3.7"
services:
  app:
    build:
      context: .
    image: htmx-ruby
    volumes:
      - ".:/opt/server"
      - "./tasks/payments.json:/opt/server/payments.json"
      - "./public:/opt/server/public"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file:
      - .env
    command: bundle exec rackup -p 8080 -o 0.0.0.0 config.ru
